
[tool.pytest.ini_options]
minversion = "6.0"
addopts =  "--junitxml=out/test/junit/test-results.xml --cov=src --cov-report=xml:out/test/junit/coverage.xml"
testpaths = [ "test" ]
filterwarnings = [
    "error",
    "ignore::DeprecationWarning"
]